django_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("team", TemplateView.as_view(template_name="team.html"), name="team",),
    path("about", TemplateView.as_view(template_name="about.html"), name="about",),
    path("accounts/", include("users.urls")),
]

urlpatterns += [
    path(
        "accounts/password_change/",
        PasswordChangeView.as_view(template_name="registration/password_change.html"),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "accounts/login/", LoginView.as_view(template_name="registration/login.html"), name="login"
    ),
    path(
        "accounts/logout/",
        LogoutView.as_view(template_name="registration/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password_reset/",
        PasswordResetView.as_view(template_name="registration/password_reset.html"),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += [
    path("stock_home/", include("stock_home.urls")),
]

users/urls.py
"""Accounts app URL Configuration."""
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("list", views.UserListView.as_view(), name="custom_user_list"),
    path("<int:pk>/", views.UserDetailView.as_view(), name="custom_user_detail"),
    path("<int:pk>/update/", views.UserUpdateView.as_view(), name="custom_user_update"),
    path("<int:pk>/delete/", views.UserDeleteView.as_view(), name="custom_user_confirm_delete"),
]

users/models.py
"""Accounts models."""
from email.policy import default

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager


class CustomUser(AbstractUser):
    """Return a custom User model.

    Arguments:
    ---------
    AbstractUser : class
        Django's `AbstractUser` class.

    Returns:
    -------
    object:
        `CustomUser` model.

    """

    IA = "Inidvidual"
    FA = "Foreign Citizen"
    UT = "US Trust"
    FT = "Foreign Trust"
    UC = "US Corporation"
    FC = "Foreign Corporation"
    PC = "Partnership/Limited Liability Company"
    MF = "Managed Futures"
    account_types = [
        (IA, "Individual"),
        (FA, "Foreign Citizen"),
        (UT, "US Trust"),
        (FT, "Foreign Trust"),
        (UC, "US Corporation"),
        (FC, "Foreign Corpoartion"),
        (PC, "Partnership/Limited Liability Company"),
        (MF, "Managed Futures"),
    ]

    id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length=30, default="")
    last_name = models.CharField(max_length=30, default="")
    email = models.EmailField(unique=True)
    password = models.CharField("User's password", max_length=88)
    buying_power = models.FloatField(default=0)
    account_value = models.FloatField(default=0)
    account_type = models.CharField(max_length=37, choices=account_types, default=IA)
    username = None

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self) -> str:
        """Return string representation of the object.

        Returns:
        -------
        str
            The unique identifer of the model, `email`.

        """
        return self.email

users/forms.py
"""Forms for accounts app."""
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """Registration form."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
            "account_type"
        )
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.TextInput(attrs={"class": "form-control"}),
            "password2": forms.TextInput(attrs={"class": "form-control"}),
            "account_type": forms.TextInput(attrs={"class": "form-control"}),
        }


class CustomUserChangeForm(forms.ModelForm):
    """User profile change view."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "email",
            "account_type"
        )

users/views.py
"""Accounts view."""
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from users.forms import (
    CustomUserCreationForm,
    CustomUserChangeForm
)
from users.models import CustomUser


class SignUpView(generic.CreateView):
    """User registration view.

    Arguments:
    ---------
    generic : object
        Django generic `CreateView`.

    """

    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


class UserListView(LoginRequiredMixin, generic.ListView):
    """User List class."""

    model = CustomUser
    template_name = "custom_user_list.html"


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    """User Detail class."""

    model = CustomUser
    template_name = "custom_user_detail.html"

    def get(self, request: object, *args, **kwargs) -> object:
        """If user is not the owner of the object, redirect."""
        if self.get_object() != self.request.user:
            return redirect("users:custom_user_list")
        return super().get(request, *args, **kwargs)


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    """User update view."""

    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = "custom_user_update.html"
    # which page to show upon success
    success_url = reverse_lazy("users:custom_user_list")

    def get(self, request: object, *args, **kwargs) -> object:
        """If user is not the owner of the object, redirect."""
        if self.get_object() != self.request.user:
            return redirect("users:custom_user_list")
        return super().get(request, *args, **kwargs)


class UserDeleteView(LoginRequiredMixin, generic.DeleteView):
    """<SomeModel> delete view."""

    model = CustomUser
    template_name = "custom_user_confirm_delete.html"
    # which page to show upon success
    success_url = reverse_lazy("users:custom_user_list")

    def get(self, request: object, *args, **kwargs) -> object:
        """If user is not the owner of the object, redirect."""
        if self.get_object() != self.request.user:
            return redirect("users:custom_user_list")
        return super().get(request, *args, **kwargs)

users/templates/about.html
{% extends "base_generic.html" %}
{% block title %}
    Stock Home
{% endblock title %}
{% block content %}
    <div class="container py-5">
        <p style="text-align: justify;">
            Stock Home is a web-based stock trading solution that provides users access to real-time, as well as historical, 
            stock data, a comission-free brokerage account for trading, and a wealth of documentation geared toward ensuring 
            users can be educated on risks, strategies, and terminology. Unlike other popular online brokerage applications, 
            Stock Home provides community forums for investors to discuss and share notes on the stock market and collects 
            information on trader sentiment through these forums. Stock Home is intender for novice and experienced investors 
            alike who want to take control of their finances and invest in their future.
        </p>
        <div style="text-align: center;">
            <strong>Keep the money coming back!</strong>
        </div>
    </div>
{% endblock content %}

users/templates/base_generic.html
{# Load the tag library #}
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="us-en">
    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Stock Home" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="author" content="John Doe" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'img/stock_home_logo.png' %}"/>
        <title>Stock Home</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link href="{% static 'fontawesomefree/css/all.min.css' %}"
              rel="stylesheet"
              type="text/css"/>
        {% block style %}
        {% endblock style %}
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container">
            <h1 class="text-center fw-bold mb-5">
                {% block title %}
                {% endblock title %}
            </h1>
            {% block content %}
            {% endblock content %}
        </div>
        {% include "footer.html" %}
    </body>
</html>

users/templates/custom_user_confirm_delete.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}User Delete{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
             <p>Are you sure you want to delete "{{ object }}"?</p>
                {% bootstrap_form form %}
              {{ form.media }}
                <div class="text-center">
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/custom_user_detail.html
{% extends "base_generic.html" %}
{% block content %}
<ul>
        <li>ID: {{ object.id}}</li>
        <li>Name: {{ object.name }}</li>
        <li>Email: {{ object.email }}</li>
        <li>Password: {{ object.password }}</li>
        <li>Buying Power: ${{ object.buying_power }}</li>
        <li>Account Value: ${{ object.account_value }}</li>
        <li>Account Type: {{ object.account_type}}</li>
</ul>
{% endblock content %}

users/templates/custom_user_list.html
{% extends "base_generic.html" %}
{% block content %}
{% if object_list %}
<ul>
{% for object in object_list %}
        <li>
<a href="{% url 'users:custom_user_detail' object.id %}">
{{ object }}
</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>No Positions are available.</p>
{% endif %}
{% endblock content %}

users/templates/custom_user_update.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}User Update{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {{ form.media }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/footer.html
<footer class="footer pt-3 mt-4 text-muted">
    <div class="container">
        Stock Home is powered by
        <a target="_blank" href="https://getbootstrap.com/">Bootstrap</a>
        and
        <a target="_blank" href="https://fontawesome.com/">Font awesome</a>.
    </div>
</footer>

users/templates/home.html
{% extends "base_generic.html" %} {% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="py-5">
    <h1 class="display-3 fw-bold">Stock Home</h1>
    <p>
      Stock Home is a web-based stock trading solution that provides access to historical and
      real-time stock data, commission-free trading, and extensive documentation to ensure that
      users can be educated on all aspects of trading, such as risks, strategies, and terminology.
      Stock Home is intended for investors of any experience level to take control of their finances
      and invest in their future.
    </p>
    <p class="col-md-8 fs-4">
      <a class="btn btn-primary btn-lg" href="{% url 'about' %}" role="button">Learn more</a>
    </p>
  </div>
</div>
<div class="py-5">
  <div class="row align-items-md-stretch">
    <div class="col-md-6">
      <div class="h-100 p-5 bg-light rounded-3">
        <p>
          Unlike other popular brokerage applications, such as Robinhood and Webull, Stock Home
          offers public discussion forums to allow users to share their analyses or collect
          information on stock sentiment, in addition to traditional forecasts and market analysis
          tools.
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="h-100 p-5 bg-light rounded-3">
        <p>
          Stock Home also provides users with lessons to familiarize themselves with investing in
          the stock market. Users can search for lessons in a specific topic, view recommended
          lessons, or view all lessons available, while Stock Home saves user progress.
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark justify-content-between">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img
                style="
                width: 2.5em;
                height: 2.5em;
                border-radius: 50%;
                "
                src="{% static 'img/stock_home_logo.png' %}"
            > Stock Home
        </a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="#navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">
                        <i class="fa-solid fa-circle-info"></i> About
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'team' %}">
                        <i class="fa-solid fa-people-group"></i> Team
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="stock_home">
                        <i class="fa-solid fa-sack-dollar"></i> App
                    </a>
                </li>
            </ul>
        </div>
        <div class="navbar-collapse collapse" id="#navbarsExampleDefault">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle"
                           role="button"
                           data-toggle="dropdown"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fa-solid fa-user-shield"></i> {{ user.email }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'password_change' %}">
                                    <i class="fa-solid fa-user-cog"></i> Change password
                                </a>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    <i class="fa-solid fa-sign-out-alt"></i> Log out
                                </a>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">
                            <i class="fa-solid fa-sign-in"></i> Sign in
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">
                            <i class="fa-solid fa-user-edit"></i> Sign up
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

users/templates/team.html
{% extends "base_generic.html" %}
{% load static %}
{% block style %}
{% endblock style %}
{% block title %}
    Meet our team
{% endblock title %}
{% block content %}
    <div class="justify-content-center">
        <div class="text-center d-flex">
            <div class="col-md-3 col-sm-6 mb-4">
                <img
                    style="
                    width: 10em;
                    height: 10em;
                    border-radius: 50%;
                    "
                    src="../static/img/blake.jpg"
                >

                <!-- Replace 'Name' with the Project Lead's name -->
                <h4 class="fw-bold">Blake Blanchard</h4>
                <p class="fw-bold">Project Lead</p>
                <!-- Update hrefs with the URLs to email, linked, and gitlab -->
                <a href="mailto: c00411322@louisiana.edu" target="_blank"><i class="fa-solid fa-envelope"></i></a> |
                <a href="https://www.linkedin.com/in/blake-blanchard-332a4117b/" target="_blank"><i class="fa-brands fa-linkedin"></i></a> |
                <a href="https://gitlab.com/blake_blanchard" target="_blank"><i class="fa-brands fa-gitlab"></i></a>
            </div>

            <div class="col-md-3 col-sm-6 mb-4">
                <img
                    style="
                    width: 10em;
                    height: 10em;
                    border-radius: 50%;
                    "
                    src="../static/img/nickh.jpg"
                >

                <!-- Replace 'Name' with the Tech Lead's name -->
                <h4 class="fw-bold">Nicholas Ho</h4>
                <p class="fw-bold">Flex Lead</p>
                <!-- Update hrefs with the URLs to email, linked, and gitlab -->
                <a href="mailto: c00119341@louisiana.edu" target="_blank"><i class="fa-solid fa-envelope"></i></a> |
                <a href="https://www.linkedin.com/in/ho-nicholas" target="_blank"><i class="fa-brands fa-linkedin"></i></a> |
                <a href="https://gitlab.com/snicholasho" target="_blank"><i class="fa-brands fa-gitlab"></i></a>
            </div>

            <div class="col-md-3 col-sm-6 mb-4">
                <img
                    style="
                    width: 10em;
                    height: 10em;
                    border-radius: 50%;
                    "
                    src="../static/img/nickr.jpg"
                >

                <!-- Replace 'Name' with the Product Lead's name -->
                <h4 class="fw-bold">Nicholas Russell</h4>
                <p class="fw-bold">Flex Lead</p>
                <!-- Update hrefs with the URLs to email, linked, and gitlab -->
                <a href="mailto: c00415058@louisiana.edu" target="_blank"><i class="fa-solid fa-envelope"></i></a> |
                <a href="https://www.linkedin.com/in/nicholas-a-russell/" target="_blank"><i class="fa-brands fa-linkedin"></i></a> |
                <a href="https://gitlab.com/Nicholas_Russell" target="_blank"><i class="fa-brands fa-gitlab"></i></a>
            </div>

            <div class="col-md-3 col-sm-6 mb-4">
                <img
                    style="
                    width: 10em;
                    height: 10em;
                    border-radius: 50%;
                    "
                    src="../static/img/gabe.jpeg"
                >

                <!-- Replace 'Name' with the QA's name -->
                <h4 class="fw-bold">Gabriel Trahan</h4>
                <p class="fw-bold">Flex Lead</p>
                <!-- Update hrefs with the URLs to email, linked, and gitlab -->
                <a href="mailto: c00058009@louisiana.edu" target="_blank"><i class="fa-solid fa-envelope"></i></a> |
                <a href="https://theokoles7.github.io/portfolio/" target="_blank"><i class="fa-brands fa-github"></i></a> |
                <a href="https://gitlab.com/THEOKOLES" target="_blank"><i class="fa-brands fa-gitlab"></i></a>
            </div>
        </div>
    </div>
{% endblock content %}